config/routes.rb
Rails.application.routes.draw do
  resources :board_messages
  resources :board_users
  devise_for :accounts
  root to: 'board_messages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user
  after_create_commit { MessageBroadcastJob.perform_later self }

  validates :content, presence:{message:'は、必須事項です。'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :account
  has_many :board_message

  validates :nickname, presence:{message:'は、必須項目です。'}
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_board_message, only: [:show, :edit, :update, :destroy]

  # GET /board_messages
  # GET /board_messages.json
  def index
    @messages = BoardMessage.all
    users=BoardUser.where'account_id==?',current_account.id
    if users[0]==nil then
     user=BoardUser.new
     user.account_id=current_account.id
     user.nickname='<<no name>>'
     user.save
     users=BoardUser.where'account_id==?',current_account.id
    end
  end

  # GET /board_messages/1
  # GET /board_messages/1.json
  def show
    redirect_to'/board_messages'
  end

  # GET /board_messages/new
  def new
    redirect_to'/board_messages'
  end

  # GET /board_messages/1/edit
  def edit
    redirect_to'/board_messages'
  end

  # POST /board_messages
  # POST /board_messages.json
  def create
    @board_message = BoardMessage.new(board_message_params)

    respond_to do |format|
      if @board_message.save
        format.html { redirect_to @board_message, notice: 'Board message was successfully created.' }
        format.json { render :show, status: :created, location: @board_message }
      else
        format.html { render :new }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_messages/1
  # PATCH/PUT /board_messages/1.json
  def update
    redirect_to'/board_messages'
  end

  # DELETE /board_messages/1
  # DELETE /board_messages/1.json
  def destroy
    redirect_to'/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_message
      @board_message = BoardMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_message_params
      params.require(:board_message).permit(:content, :board_user_id)
    end
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :set_board_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!

  #layout 'board_users'　#必要に応じて用意

  # GET /board_users
  # GET /board_users.json
  def index
   users=BoardUser.where'account_id==?',current_account.id
   if users[0]==nil then
    user=BoardUser.new
    user.account_id=current_account.id
    user.nickname='<<no name>>'
    user.save
    users=BoardUser.where'account_id==?',current_account.id
   end
   @board_user=users[0]
  end

  # GET /board_users/1
  # GET /board_users/1.json
  def show
    @board_user=BoardUser.find params[:id]
  end

  # GET /board_users/new
  def new
    redirect_to'/board_messages'
  end

  # GET /board_users/1/edit
  def edit
    redirect_to'/board_messages'
  end

  # POST /board_users
  # POST /board_users.json
  def create
    redirect_to'/board_messages'
  end

  # PATCH/PUT /board_users/1
  # PATCH/PUT /board_users/1.json
  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        format.html { redirect_to'/board_messages' }
        format.json { render :show, status: :ok, location: @board_user }
      else
        format.html { render :index }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_users/1
  # DELETE /board_users/1.json
  def destroy
    redirect_to'/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_user
      @board_user = BoardUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_user_params
      params.require(:board_user).permit(:nickname, :account_id, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/views/board_messages/_form.html.erb
<%= form_with(model: board_message, local: true) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_message.errors.count, "error") %> prohibited this board_message from being saved:</h2>

      <ul>
      <% board_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :board_message_content %>
  </div>

  <div class="field">
    <%= form.label :board_user_id %>
    <%= form.number_field :board_user_id, id: :board_message_board_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_messages/index.html.erb
<p><%= link_to'マイページ >>',controller: :board_users %></p>
<h1>Chat Room</h1>

<div id="messages">
  <% @messages.each do |obj| %>
    <div class="messages-index-item" id="<%= obj.id %>">
      <%= link_to obj.board_user.nickname,controller: :board_users,action: :show,id:obj.board_user_id %>
      :<b><%= obj.content %></b>
      <font size="1"><%= obj.created_at %></font>
      <% if obj.board_user.id==current_account.id %>
        <button id="<%=obj.id%>" class="delete-btn">削除</button>
      <% end %>
      <br>
    </div>
  <% end %>
</div>
<br>
<form id="room_speaker">
  <label>エンターキーで発言する:</label>
  <input type="text" id="message">
  <input type="hidden" id="id" value=<%= current_account.id %>>
</form>
<br>
<div><%= link_to"ログアウト&gt;&gt;".html_safe,destroy_account_session_path,method: :delete %></div>

<script>
$(function(){
    $(document).on('keypress','#room_speaker',function(e){
      if(e.keyCode==13){
        App.room.speak(message.value,id.value);
        message.value = ''
        e.preventDefault()
      }
    });
});
</script>

app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_users/_form.html.erb
<%= form_with(model: board_user, local: true) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %> prohibited this board_user from being saved:</h2>

      <ul>
      <% board_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
  <tr class="field">
    <th>ニックネーム</th>
    <td><%= form.text_field :nickname, id: :board_user_nickname %></td>
  </tr>

  <%= form.hidden_field :account_id %>

  <tr class="field">
    <th>自己紹介</th>
    <td><%= form.text_area :memo, id: :board_user_memo %></td>
  </tr>

  <tr class="actions">
    <th></th><td><%= form.submit value: "変更" %></td>
  </tr>
  </table>
<% end %>

app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

app/views/board_users/index.html.erb
<h1>マイページ</h1>
<h2>※<%= @board_user.account.email %>さんの設定</h2>
<%= render 'form',board_user: @board_user %>
<hr>
<p><%= link_to '<< 戻る',controller: :board_messages %></p>

app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

app/views/board_users/show.html.erb
<h1>"<%= @board_user.nickname %>"さんの情報</h1>
<table>
<tr>
  <th>ニックネーム:</th>
  <td><%= @board_user.nickname %></td>
</tr>

<tr>
  <th>Id:</th>
  <td><%= @board_user.id %></td>
</tr>

<tr>
  <th>登録日:</th>
  <td><%= @board_user.created_at %></td>
</tr>

<tr>
  <th>自己紹介:</th>
  <td><%= @board_user.memo %></td>
</tr>

</table>

<tr>
  <b>過去の書き込み:</b>
    <% @board_user.board_message.each do |obj| %>
    <br><td><%= obj.content %></td>
  <% end %>
</tr>


<hr>
<%= link_to '<< 戻る',controller: :board_messages %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railschat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- /jQueryを読み込む -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <%= link_to message.board_user.nickname,controller: :board_users,action: :show,id:message.board_user_id %>
  :<b><%= +message.content %></b>
  <font size="1"><%= message.created_at %></font>
</div>